const {test}=require('node:test');
const assert=require('node:assert/strict');
const {createSession}=require('../extension/session.js');
const user={id:'7'};
const snapshot=(age=0)=>({user,origin:'https://school.instructure.com',courses:[],assignments:[],fetchedAt:new Date(Date.now()-age).toISOString()});
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
function fixture(cached,network){const events=[];let reads=0,writes=0,destroyed=0;const store={load:async()=>{},readCache:async()=>{reads++;return cached;},writeCache:async()=>{writes++;},destroy:()=>destroyed++};const client={profile:async()=>user,loadSnapshot:network};const session=createSession({client,createStore:()=>store,onSnapshot:(value,s,meta)=>events.push({value,s,meta}),onStatus:()=>{},onError:()=>{}});return {session,events,client,get reads(){return reads;},get writes(){return writes;},get destroyed(){return destroyed;}};}
test('fresh account-verified cache renders without downloading every course again',async()=>{let fetches=0;const f=fixture(snapshot(),async()=>{fetches++;return snapshot();});await f.session.start();assert.equal(f.events.length,1);assert.equal(f.events[0].meta.stale,false);assert.equal(fetches,0);assert.equal(f.reads,1);f.session.destroy();});
test('stale cache is shown before a slow background refresh completes',async()=>{const network=deferred(),f=fixture(snapshot(600000),()=>network.promise);const task=f.session.start();await new Promise(setImmediate);assert.equal(f.events.length,1);assert.equal(f.events[0].meta.stale,true);network.resolve(snapshot());await task;assert.equal(f.events.length,2);assert.equal(f.events[1].meta.stale,false);assert.equal(f.writes,1);f.session.destroy();});
test('identity must succeed before personal data or cached courses are read',async()=>{const f=fixture(snapshot(),async()=>snapshot());f.client.profile=async()=>{const e=Error('Signed out');e.code='auth';throw e;};await f.session.start();assert.equal(f.reads,0);assert.equal(f.events.length,0);f.session.destroy();});
test('account change during refresh clears displayed personal content',async()=>{const f=fixture(snapshot(),async()=>({...snapshot(),user:{id:'8'}}));let cleared=0;f.session.destroy();const session=createSession({client:f.client,createStore:()=>({load:async()=>{},readCache:async()=>snapshot(),writeCache:async()=>{throw Error('wrong account must not be cached');},destroy:()=>{}}),onSnapshot:()=>{},onStatus:()=>{},onError:(_e,{clear})=>{if(clear)cleared++;}});await session.start();await session.refresh();assert.equal(cleared,1);session.destroy();});
test('closing the page during refresh cannot render late data',async()=>{const network=deferred(),f=fixture(null,()=>network.promise);const task=f.session.start();await new Promise(setImmediate);f.session.destroy();network.resolve(snapshot());await task;assert.equal(f.events.length,0);assert.equal(f.writes,0);assert.equal(f.destroyed,1);});
test('overlapping refresh actions share one network refresh',async()=>{const network=deferred();let fetches=0;const f=fixture(snapshot(),()=>{fetches++;return network.promise;});await f.session.start();const first=f.session.refresh(),second=f.session.refresh();network.resolve(snapshot());await Promise.all([first,second]);assert.equal(fetches,1);f.session.destroy();});
